import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // Manual sidebar for textbook content
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Physical AI Fundamentals',
      items: [
        'physical-ai/introduction',
        'physical-ai/embodied-intelligence',
        'physical-ai/robot-locomotion',
      ],
    },
    {
      type: 'category',
      label: 'Humanoid Robotics',
      items: [
        'humanoid-robotics/hardware',
        'humanoid-robotics/control-systems',
        'humanoid-robotics/perception',
      ],
    },
    {
      type: 'category',
      label: 'Software Platforms',
      items: [
        'software/ros2',
        'software/gazebo',
        'software/nvidia-isaac',
      ],
    },
    {
      type: 'category',
      label: 'AI Integration',
      items: [
        'ai/vision-language-action',
        'ai/personalization',
        'ai/translation',
      ],
    },
    {
      type: 'category',
      label: 'Interactive Features',
      items: [
        'interactive/rag-chatbot',
        'interactive/personalization',
        'interactive/translation',
      ],
    },
  ],
};

export default sidebars;
